/* Generated by AN DISI Unibo */ 
package it.unibo.transporttrolley

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Transporttrolley ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outyellow("$name START, engage basicrobot ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("waitCmd") { //this:State
					action { //it:State
						CommUtils.outyellow("$name | waiting for commands ...	")
						updateResourceRep( "$name(waiting) "  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t06",targetState="moveToIndoor",cond=whenRequest("gomoveToIndoor"))
				}	 
				state("moveToIndoor") { //this:State
					action { //it:State
						CommUtils.outyellow("$name moveToIndoor ")
						request("moverobot", "moverobot(0,4)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t07",targetState="loadTheCharge",cond=whenReply("moverobotdone"))
					transition(edgeName="t08",targetState="failedMovement",cond=whenReply("moverobotfailed"))
				}	 
				state("failedMovement") { //this:State
					action { //it:State
						CommUtils.outyellow("robot not moving ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("loadTheCharge") { //this:State
					action { //it:State
						updateResourceRep( "$name(loading) "  
						)
						CommUtils.outyellow("$name loading charge ... ")
						forward("chargeTaken", "chargeTaken(_)" ,"coldstorageservice" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="moveToColdRoom", cond=doswitch() )
				}	 
				state("moveToColdRoom") { //this:State
					action { //it:State
						CommUtils.outyellow("$name moveToColdRoom")
						request("moverobot", "moverobot(4,3)" ,"basicrobot" )  
						delay(2000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t09",targetState="storeTheCharge",cond=whenReply("moverobotdone"))
				}	 
				state("storeTheCharge") { //this:State
					action { //it:State
						updateResourceRep( "$name(storing) "  
						)
						CommUtils.outyellow("$name storing charge ... ")
						delay(2000) 
						 CommUtils.waitTheUser("$name loading charge. Please HIT ")  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="moveToHome", cond=doswitch() )
				}	 
				state("moveToHome") { //this:State
					action { //it:State
						CommUtils.outgreen("$name moveToHome ")
						request("moverobot", "moverobot(0,0)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t010",targetState="trolleyAtHome",cond=whenReply("moverobotdone"))
				}	 
				state("trolleyAtHome") { //this:State
					action { //it:State
						CommUtils.outgreen("$name trolley at home ")
						forward("setdirection", "dir(down)" ,"basicrobot" ) 
						updateResourceRep( "$name(athome) "  
						)
						delay(2000) 
						forward("disengage", "disengage(transporttrolley)" ,"basicrobot" ) 
						delay(1000) 
						 System.exit(0)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
}
